services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_DATABASE:db
      - MYSQL_USER:docker
      - MYSQL_PASSWORD:docker
    networks:
      - docker-network

  api-docker:
    container_name: api-docker
    build:
      context: .
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
